type Query {
  """
  Fetch all products
  """
  products: [Product]
  """
  Fetch product by id
  """
  product(id: ID!): Product
  # availableProducts: [Product]
}

type Mutation {
  createProduct(
    name: String!
    price: Float!
    image: String!
    categoryId: Int!
  ): Product
}

type Product @key(fields: "categories") {
  id: ID!
  name: String
  image: String
  price: Float
  categories: [Category]
  # availability: Availability!
}

# enum Availability {
#   IN_STOCK
#   TEMPORARILY_UNAVAILABLE
#   OUT_OF_ASSORTMENT
# }

extend type Category @key(fields: "categoryId") {
  categoryId: Int! @external
  products: [Product]
}
