type Query {
  products: [Product]
  product(id: ID!): Product
}

type Mutation {
  createProduct(name: String!, price: Float!, image: String!, categoryId: Int!): Product
}

type Product @key(fields: "categories") {
  id: ID!
  name: String
  image: String
  price: Float
  categories: [Category]
}

extend type Category @key(fields: "categoryId") {
  categoryId: Int! @external
  products: [Product]
}
