type Query {
  """
  Fetch all categories
  """
  categories: [Category]
  """
  Fetch category by category id
  """
  category(
    """
    Category id as human readable integer
    """
    categoryId: Int!
    ): Category
}

type Category @key(fields: "categoryId") {
  id: ID!
  categoryId: Int!
  name: String!
}

extend type Product @key(fields: "categories") {
  categories: [Category] @external
}
